title: "Business Practicum"
theme: jekyll-theme-minimal

description: >
  By Zhaohu (Jonathan) Fan <br />  <br /> <br /> <br />
  "Learn by doing: real partners, real projects, real impact."

show_downloads: false
github:
  is_project_page: false
