title: "Business Practicum"
theme: jekyll-theme-minimal

description: > 
  "Learn by doing: real partners, real projects, real impact."
logo: "https://github.com/jonathanatuscpsu/business-practicum/blob/f85c31056fd8425f8a84f58ce677ca76852b2a85/12-1.jpg"
show_downloads: false
github:
  is_project_page: false
