title: "Business Practicum"
theme: jekyll-theme-minimal

description: >
  Learn by doing: real partners, real projects, real impact.

logo: "https://github.com/jonathanatuscpsu/business-practicum/raw/main/12-1.jpg"
show_downloads: false

github:
  is_project_page: false
